name = "cf-events"
main = "src/index.ts"
compatibility_date = "2024-02-08"

[placement]
mode = "smart"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Note: Use secrets to store sensitive data.
# Docs: https://developers.cloudflare.com/workers/platform/environment-variables
[vars]
ALLOW_ORIGIN = "https://my-website.com"

[[d1_databases]]
binding = "DB"
database_name = "your-database-name"
database_id = "...your id here..."
